[project]
name = "uppaal-creator"
version = "0.1.0"
dependencies = ["pyuppaal", "networkx", "pydot"]
requires-python = ">= 3.10"

[tool.autoflake]
check = true
expand_star_imports = true
remove_all_unused_imports = true
